# Site wide configuration

title: "Marco di Biase"
description: "My personal page with all my info, links, etc."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year/:month/:day/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner: 
  name: Marco di Biase
  email:
  twitter: mardibiase
  google:
    ad-client:
    ad-slot:
  bio:
  avatar:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", 
          "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", 
          "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", 
          "package.json"]
